---
description: "This is the notes for your_module_name"
---

# Introduction to Quarto Bookdown

This is a template to create notes in Quarto bookdown. For more information on Quarto bookdown please see [this website.](https://quarto.org/?target=_blank)

::: note
This template is based on the previous version of the R Bookdown template. If you find any issues or have any suggestions, please add a discussion in out GitHub repository.
Additionally, you may find some of the old R Bookdown files are not used in this template, but they are kept for reference in `other` folder.
:::

## Quarto Bookdown Installation

::: note
If you do not already have R and IDE installed on your computer, go to the [RStudio Desktop download page](https://posit.co/download/rstudio-desktop/?target=_blank) and follow the instructions to install (1) R and (2) RStudio.
:::

### Install Quarto Bookdown {-}

Then, go to the Quarto official website to download the quarto package. Here is [the link](https://quarto.org/docs/get-started/?target=_blank).

## Compile a Book
Follow the steps below to download and compile the source code for this template in Quarto Bookdown.

1) Download this project using Github. (You can directly go to the GitHub page by clicking the sidebar icon)
2) Install the Quarto extension for your IDE, such as VSCode, IntelliJ or RStudio.

:::tip
Instructions for unzipping files: [[Windows](https://support.microsoft.com/en-us/windows/zip-and-unzip-files-f6dde0a7-0fec-8294-e1d3-703ed85e7ebc?target=_blank), [MacOS](https://support.apple.com/en-gb/guide/mac-help/mchlp2528/mac#:~:text=Unzip%20(expand)%20a%20compressed%20item,zip%20file.?target=_blank), [Linux](https://unstop.com/blog/how-to-unzip-a-file-in-linux?target=_blank)]
Moreover, in some new IDEs, you can directly clone the project by entering the GitHub URL.
:::

3) Open the terminal (make sure you are in the root directory of the project), and type the following command:

``` bash
quarto render
```

4) To view your book outside of RStudio, navigate to the "_book" subfolder that was created when you compiled your book, then open `index.html` in your favourite browser. Or you can simply set up a local server by running the following command in the terminal:

``` bash
quarto preview
```

## Upload Your Book to Moodle
Please watch the video guide below.

If the link does not work then [please click here.](https://mediaspace.nottingham.ac.uk/media/How+to+upload+R+bookdown+file+to+Moodle/1_la5eitil)

<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/1355621/sp/135562100/embedIframeJs/uiconf_id/13188771/partner_id/1355621?iframeembed=true&playerId=kaltura_player&entry_id=1_la5eitil&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[hotspots.plugin]=1&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;" width="456" height="292" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe>

Please watch the video guide below.

If the link does not work then [please click here.](https://mediaspace.nottingham.ac.uk/media/Clip+of+How+to+upload+R+Bookdown+html+to+Moodle/1_9hm74lrs)

<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/1355621/sp/135562100/embedIframeJs/uiconf_id/13188771/partner_id/1355621?iframeembed=true&playerId=kaltura_player&entry_id=1_9hm74lrs&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[hotspots.plugin]=1&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_0ysdz76w" width="456" height="292" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Clip of How to upload R Bookdown html to Moodle"></iframe>
